### ISSUE TITLE
JustinaSetup.sh dependence of "apt-get update"

### ISSUE THREAD

**Issue by rag21** [RobotJustina/JUSTINA#8]
![error1](https://cloud.githubusercontent.com/assets/15699389/16054633/a0017e88-3233-11e6-875a-248b52d2ddec.png)
![error2](https://cloud.githubusercontent.com/assets/15699389/16054634/a0025470-3233-11e6-8685-05a94a59913d.png)
error1 was dropped by justinaSetup.sh, error2 was dropped by "sudo apt-get update"
As I try to expose with the two attached images, JustinaSetup.sh fails if "sudo apt-get update" returns an error code, I think it's a good way to ensure the user dependencies, but sometimes there are some situations when this isn't the most suitable way (especially if the user mess with his own package sources). I suggest that the installation must continue even if there are unsatisfied fetch files, and later check if such fetch files concerns to justina dependencies.

**Comment by kyordhel** [comment]
The problem is not related to JustinaSetup.sh, but to that machine having installed Google Chrome (which shouldn't be there).

That's a common issue that occurs when Google deprecates a version of Chrome and does not update the repos with the new servers.

[Check here](http://www.omgubuntu.co.uk/2016/03/fix-failed-to-fetch-google-chrome-apt-error-ubuntu)

**Comment by rag21** [comment]
I know it's a chrome problem, thats exactly what I'm talking about, even with that issues the justinaScript must continue, you can't expect that the user solves every problem on his system in order to execute the script.

**Comment by kyordhel** [comment]
I fear you are not understanding how a Setup script works.

The Justina Script must **NOT** continue on error, since fixing an error at OS level is beyond automation. There is no way for me to know if apt-get update failed because of a problem in dependencies, corrupt data, lack of internet access, etc.

Even more, if the apt-get update command fails, the apt-get install will also fail, therefore, nothing can be installed, and if new files are not downloaded, configuration files cannot be created.

This script is meant to be run by engineers. Should I be developing for general use, I would not include software in testing mode, and it were to be sent to peer-review before integrating it in the common repositories of ubuntu.

**Comment by kyordhel** [comment]
Deprecated.
